name: Deploy to EC2

on:
  push:
    branches: [ master ]  # or 'main', depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd ~/app
          git pull origin master
          docker-compose down
          docker-compose build
          docker-compose up -d --force-recreate